language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script::
  - npm run build

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --project ccc-mercer-co --token 1/tU9Uhb9_3yKl0a83kOlHTElwO_0pmj5Z-ZxzfWvqdBc
